title: Jacob's Pages 
description: "Class of 2025"
owner_name: Jacob Zierolf
github_username: jacobcancode
github_repo: "jacob_2025" 
baseurl: "/jacob_2025"
future: true
remote_theme: pages-themes/midnight@v0.2.0
timeout: 60
minima:
  skin: Dark
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders"}
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" } 
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/blog.md
  - navigation/search.md
  - navigation/about.md
  - navigation/games.md
  - README4YML.md